#!/usr/bin/env python3
import os
import json

BASE_DIR = "/home/mesuto/Documents/PROJELER/duru_okul/havo3/engels"
DATA_DIR = os.path.join(BASE_DIR, "js/data")
os.makedirs(DATA_DIR, exist_ok=True)

def balance_mc(questions):
    mc_indices = [i for i, q in enumerate(questions) if q.get("type") == "mc"]
    target_pattern = [0, 1, 2, 3] * (len(mc_indices) // 4 + 2)
    for idx, q_idx in enumerate(mc_indices):
        q = questions[q_idx]
        current_ans_idx = q["antwoord"]
        correct_text = q["opties"][current_ans_idx]
        new_ans_idx = target_pattern[idx] % len(q["opties"])
        if new_ans_idx != current_ans_idx:
            opts = [opt for i, opt in enumerate(q["opties"]) if i != current_ans_idx]
            opts.insert(new_ans_idx, correct_text)
            q["opties"] = opts
            q["antwoord"] = new_ans_idx

def write_examen(filename, data):
    balance_mc(data["vragen"])
    path = os.path.join(DATA_DIR, filename)
    content = f"""/* Proeftoets {data['titel']}
   Stepping Stones 3 HAVO Hoofdstuk {data['hoofdstuk']} */
DURU.registerExamen({json.dumps(data, indent=2, ensure_ascii=False)});
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [✓] Examen saved: {filename}")

# EXAMEN 21: H5 Theme Words (Environment & Sustainability) (20 questions)
ex21 = {
  "id": "ex-h3-eng-21",
  "hoofdstuk": 5,
  "hoofdstukTitel": "Hoofdstuk 5 — Going green",
  "titel": "Toets 1 — Theme Words: Environment, Climate & Sustainability",
  "vak": "Engels · HAVO 3 (H5)",
  "icoon": "🌱",
  "duurMin": 25,
  "vragen": [
    {"type": "mc", "vraag": "Which statement provides the scientific definition of a <b>carbon footprint</b>?", "opties": ["The total amount of greenhouse gases generated by our personal actions and lifestyle", "The depth of footprints left in muddy wetlands", "A trademark symbol for eco-friendly shoes", "The black smoke produced by diesel tractors"], "antwoord": 0, "uitleg": "Carbon footprint is de totale uitstoot van broeikasgassen (CO2) door iemands levensstijl."},
    {"type": "mc", "vraag": "Which of the following is a primary source of <b>renewable energy</b>?", "opties": ["Solar radiation harnessed by photovoltaic panels", "Coal burned in thermal power stations", "Heavy crude oil refined into gasoline", "Natural gas pumped from underground reservoirs"], "antwoord": 0, "uitleg": "Zonne-energie is een onuitputtelijke hernieuwbare bron."},
    {"type": "waaronwaar", "vraag": "<b>Deforestation</b> refers to planting millions of new trees in suburban city parks.", "antwoord": False, "uitleg": "Onwaar. Deforestation is grootschalige ontbossing en bomenkap."},
    {"type": "invul", "vraag": "Fill in the English adjective for <i>bedreigd</i>: <i>The polar bear is an ... species due to melting Arctic ice.</i>", "antwoord": "endangered", "uitleg": "Endangered species betekent bedreigde diersoort."},
    {"type": "mc", "vraag": "What does the term <b>biodiversity</b> mean?", "opties": ["The variety and variability of life on Earth within a particular habitat or ecosystem", "The number of electric vehicle charging points in a municipality", "The chemical formula for pure drinking water", "The amount of plastic packaging recycled each month"], "antwoord": 0, "uitleg": "Biodiversiteit is de rijkdom aan planten- en diersoorten in een ecosysteem."},
    {"type": "waaronwaar", "vraag": "Products described as <b>eco-friendly</b> are designed to have minimal harmful impact on the environment.", "antwoord": True, "uitleg": "Waar. Eco-friendly betekent milieuvriendelijk."},
    {"type": "invul", "vraag": "Fill in the verb (recyclen / hergebruiken): <i>We must ... glass, paper, and plastic to reduce landfill waste.</i>", "antwoord": "recycle", "uitleg": "Recycle betekent recyclen / hergebruiken."},
    {"type": "mc", "vraag": "What is the primary cause of modern <b>global warming</b>?", "opties": ["Excessive emissions of greenhouse gases from burning fossil fuels and industry", "Too many electric wind turbines in coastal waters", "Planting large organic vegetable gardens in schools", "The natural cycle of moonlight reflecting off oceans"], "antwoord": 0, "uitleg": "Broeikasgassen door fossiele brandstoffen veroorzaken de opwarming van de aarde."},
    {"type": "mc", "vraag": "What does nature <b>conservation</b> involve?", "opties": ["Protecting, preserving, and managing natural habitats and wildlife species", "Building luxury holiday resorts on protected coral reefs", "Converting all forests into industrial parking lots", "Hunting wild animals for entertainment"], "antwoord": 0, "uitleg": "Conservation is het beschermen en behouden van de natuur."},
    {"type": "waaronwaar", "vraag": "<b>Organic food</b> is grown using synthetic chemical pesticides and artificial fertilizers.", "antwoord": False, "uitleg": "Onwaar. Biologisch voedsel wordt verbouwd ZONDER chemische bestrijdingsmiddelen."},
    {"type": "invul", "vraag": "Fill in the noun for <i>duurzaamheid</i>: <i>Environmental ... is the key goal of green technologies.</i>", "antwoord": "sustainability", "uitleg": "Sustainability is duurzaamheid."},
    {"type": "mc", "vraag": "What does a <b>wind turbine</b> do?", "opties": ["Converts the kinetic energy of wind into clean electrical power", "Blows cool air across cities on hot summer days", "Measures the temperature of high altitude clouds", "Extracts oil from deep offshore wells"], "antwoord": 0, "uitleg": "Een windturbine wekt schone elektriciteit op uit windenergie."},
    {"type": "open", "vraag": "Explain two practical ways a teenager can reduce their personal emissions in daily life.", "sleutelwoorden": ["cycle/bike/walk/bus/public transport", "recycle/energy/lights/meat/less"], "minTreffers": 1, "modelantwoord": "Teenagers can cycle or use public transport instead of cars, and reduce energy use by turning off lights and recycling.", "uitleg": "Fietsen/OV gebruiken en energie besparen (licht uitdoen, recyclen) verlagen de CO2-voetafdruk."},
    {"type": "mc", "vraag": "What is meant by an <b>ecosystem</b>?", "opties": ["A biological community of interacting organisms and their physical environment", "A computer system that controls school printers", "A store that sells recycled sports clothing", "A government budget for building highways"], "antwoord": 0, "uitleg": "Een ecosysteem is een leefgemeenschap van organismen en hun omgeving."},
    {"type": "waaronwaar", "vraag": "Single-use plastics take hundreds of years to decompose and pose a major threat to marine life.", "antwoord": True, "uitleg": "Waar. Plastic breekt zeer langzaam af en vervuilt oceanen."},
    {"type": "invul", "vraag": "Fill in the noun (vervuiling): <i>Air ... in major cities can cause serious respiratory illnesses.</i>", "antwoord": "pollution", "uitleg": "Pollution is vervuiling."},
    {"type": "mc", "vraag": "What is the <b>greenhouse effect</b>?", "opties": ["The trapping of the sun's warmth in the planet's lower atmosphere by greenhouse gases", "The construction of glass plant nurseries in botanical gardens", "The reflection of green sunlight by leaves in spring", "A special painting method using ecological pigments"], "antwoord": 0, "uitleg": "Het broeikaseffect houdt warmte vast in de dampkring."},
    {"type": "waaronwaar", "vraag": "Solar panels generate electricity only during nighttime when temperatures are cold.", "antwoord": False, "uitleg": "Onwaar. Zonnepanelen werken op zonlicht gedurende de dag."},
    {"type": "invul", "vraag": "Complete the phrase: <i>We need to shift towards ... sources of energy like wind and solar.</i>", "antwoord": "renewable|sustainable|green", "uitleg": "Renewable / sustainable energy sources."},
    {"type": "mc", "vraag": "Which action contributes directly to forest conservation?", "opties": ["Planting native trees and supporting sustainable forestry certification", "Clearing woodland to build charcoal factories", "Burning fallen autumn leaves with diesel", "Dumping plastic trash in river basins"], "antwoord": 0, "uitleg": "Bomen planten en duurzaam bosbeheer beschermen bossen."}
  ]
}

# EXAMEN 22: H5 Grammar (Future Forms & First Conditional) (20 questions)
ex22 = {
  "id": "ex-h3-eng-22",
  "hoofdstuk": 5,
  "hoofdstukTitel": "Hoofdstuk 5 — Going green",
  "titel": "Toets 2 — Grammar: Future Forms & First Conditional",
  "vak": "Engels · HAVO 3 (H5)",
  "icoon": "🔮",
  "duurMin": 25,
  "vragen": [
    {"type": "mc", "vraag": "Which sentence correctly uses the <b>First Conditional</b>?", "opties": ["If we invest in renewable energy, we will reduce carbon emissions.", "If we will invest in renewable energy, we reduce carbon emissions.", "If we invest in energy, we would reduced emissions.", "If we will invest, we will reduce."], "antwoord": 0, "uitleg": "If + Present Simple (invest), resultaat = will + hele werkwoord (will reduce)."},
    {"type": "mc", "vraag": "Look at those dark storm clouds gathering! Which future form is correct?", "opties": ["It is going to rain very soon.", "It will rain probably next decade.", "It rains yesterday evening.", "It was raining right now."], "antwoord": 0, "uitleg": "Bij direct zichtbaar bewijs gebruik je 'be going to' (is going to rain)."},
    {"type": "waaronwaar", "vraag": "In the <i>if-clause</i> of a First Conditional sentence, you should always include <i>will</i>.", "antwoord": False, "uitleg": "Onwaar. In het if-deel gebruik je de Present Simple, NOOIT will."},
    {"type": "invul", "vraag": "Fill in the verb form: <i>If average temperatures rise, polar ice caps ... melt.</i>", "antwoord": "will", "uitleg": "Het resultaatdeel van de First Conditional krijgt 'will'."},
    {"type": "mc", "vraag": "Someone knocks on your door unexpectedly. What is your spontaneous response?", "opties": ["I'll answer it!", "I am answering it yesterday.", "I am going to answer it every morning.", "I have answered it since noon."], "antwoord": 0, "uitleg": "Voor spontane beslissingen ter plekke gebruik je 'will' / 'I'll'."},
    {"type": "waaronwaar", "vraag": "The negative form of <i>will</i> is <i>won't</i> (will not).", "antwoord": True, "uitleg": "Waar. Won't is de samentrekking van will not."},
    {"type": "invul", "vraag": "Complete the First Conditional: <i>If you ... (to turn) off standby appliances, you will save power.</i>", "antwoord": "turn", "uitleg": "If + Present Simple: turn."},
    {"type": "mc", "vraag": "Which future form is used for a fixed arrangement with a confirmed time and date?", "opties": ["Present Continuous (e.g. <i>We are meeting the mayor tomorrow at 10 AM</i>)", "Past Simple (e.g. <i>We met the mayor</i>)", "Past Continuous (e.g. <i>We were meeting</i>)", "Present Perfect (e.g. <i>We have met</i>)"], "antwoord": 0, "uitleg": "Vaste afspraken met tijd/plaats staan in de Present Continuous."},
    {"type": "mc", "vraag": "Why is <i>'If the sea will warm up, coral reefs will die'</i> grammatically incorrect?", "opties": ["The conditional 'if' clause must use the Present Simple 'warms up'", "Reefs cannot be combined with die", "Sea must be plural in conditional sentences", "Coral is an irregular adjective"], "antwoord": 0, "uitleg": "In de if-bijzin gebruik je de Present Simple: 'If the sea warms up...'."},
    {"type": "waaronwaar", "vraag": "The sentence <i>'I think electric cars will become cheaper in the future'</i> uses <i>will</i> for a personal prediction.", "antwoord": True, "uitleg": "Waar. 'Will' wordt gebruikt voor voorspellingen zonder direct bewijs."},
    {"type": "invul", "vraag": "Fill in the negative form: <i>If we don't protect the rainforest, endangered animals ... survive.</i>", "antwoord": "will not|won't", "uitleg": "Will not / won't survive."},
    {"type": "mc", "vraag": "Which question correctly forms a First Conditional sentence?", "opties": ["What will happen if we do not reduce plastic waste?", "What happens if we will not reduce plastic waste?", "What did happen if we do not reduce waste?", "What would happened if we do not reduce waste?"], "antwoord": 0, "uitleg": "What will happen + if we do not reduce."},
    {"type": "open", "vraag": "Complete this conditional sentence with a logical result: <i>'If our school installs solar panels on the roof, ...'</i>", "sleutelwoorden": ["generate/clean/electricity/power", "reduce/energy/bills/cost/save"], "minTreffers": 1, "modelantwoord": "If our school installs solar panels on the roof, we will generate clean electricity and reduce our energy bills.", "uitleg": "Het resultaatdeel moet 'will + hele werkwoord' bevatten met een logisch gevolg."},
    {"type": "mc", "vraag": "Choose the correct form: <i>We ... (to plant) 100 new oak trees this Saturday; the council already approved the plan.</i>", "opties": ["are going to plant / are planting", "planted", "have planted yesterday", "plant every century"], "antwoord": 0, "uitleg": "Een vast plan met voorbereiding -> be going to / are planting."},
    {"type": "waaronwaar", "vraag": "In First Conditional sentences, the <i>if-clause</i> can be placed either at the beginning or at the end of the sentence.", "antwoord": True, "uitleg": "Waar. 'If it rains, we will stay inside' = 'We will stay inside if it rains'."},
    {"type": "invul", "vraag": "Complete the sentence: <i>If Duru studies hard for the test, she ... get a top grade.</i>", "antwoord": "will", "uitleg": "She will get a top grade."},
    {"type": "mc", "vraag": "Which phrase expresses a promise for the future?", "opties": ["I promise I will always turn off the lights when leaving the room.", "I promise I was turning off the lights yesterday.", "I promise I turned off lights in 2010.", "I promise I turn lights."], "antwoord": 0, "uitleg": "Belofte -> 'will'."},
    {"type": "waaronwaar", "vraag": "The sentence <i>'Look out! That tree will fall!'</i> is more idiomatic than <i>'is going to fall'</i> when you see it tipping over right now.", "antwoord": False, "uitleg": "Onwaar. Bij direct zichtbaar bewijs gebruik je 'is going to fall'."},
    {"type": "invul", "vraag": "Fill in the verb (Present Simple): <i>Unless governments ... (to act) now, climate change will worsen.</i>", "antwoord": "act", "uitleg": "Unless + Present Simple: act."},
    {"type": "mc", "vraag": "What does <b>unless</b> mean in conditional sentences?", "opties": ["Except if / If not (e.g. <i>Unless we act = If we do not act</i>)", "Because of", "In addition to", "As soon as"], "antwoord": 0, "uitleg": "Unless betekent 'tenzij' (if not)."}
  ]
}

# EXAMEN 23: H5 Stones & Environmental Debates (20 questions)
ex23 = {
  "id": "ex-h3-eng-23",
  "hoofdstuk": 5,
  "hoofdstukTitel": "Hoofdstuk 5 — Going green",
  "titel": "Toets 3 — Stones & Skills: Green Proposals & Persuasive Debating",
  "vak": "Engels · HAVO 3 (H5)",
  "icoon": "🗣️",
  "duurMin": 25,
  "vragen": [
    {"type": "mc", "vraag": "Which phrase is grammatically correct when proposing an eco-friendly project?", "opties": ["Why don't we set up a bicycle repair workshop at school?", "Why don't we to set up a workshop?", "How about to set up a workshop?", "Let's to set up a workshop."], "antwoord": 0, "uitleg": "'Why don't we + hele werkwoord' (set up)."},
    {"type": "mc", "vraag": "How do you present two opposing perspectives in an environmental debate?", "opties": ["On the one hand electric cars reduce emissions, but on the other hand battery production requires rare minerals.", "Firstly we buy cars, and finally we drive them.", "Because of batteries, despite of roads.", "Since yesterday until tomorrow."], "antwoord": 0, "uitleg": "'On the one hand..., on the other hand...' weegt voor- en nadelen af."},
    {"type": "waaronwaar", "vraag": "The phrase <i>'In the long run'</i> refers to consequences that only last for the next sixty seconds.", "antwoord": False, "uitleg": "Onwaar. 'In the long run' betekent op de lange termijn."},
    {"type": "invul", "vraag": "Complete the suggestion formula: <i>How about ... (to install) smart thermostats in all classrooms?</i>", "antwoord": "installing", "uitleg": "'How about' wordt gevolgd door -ing: installing."},
    {"type": "mc", "vraag": "How do you politely acknowledge an opponent's concern before giving your counter-argument?", "opties": ["I understand your concern regarding the high initial costs, but solar panels save money over time.", "Your opinion is completely ridiculous.", "I refuse to hear any objections.", "Shut up and listen to me."], "antwoord": 0, "uitleg": "Beleefd erkennen en nuanceren."},
    {"type": "waaronwaar", "vraag": "Using verified scientific statistics strengthens your credibility in an environmental debate.", "antwoord": True, "uitleg": "Waar. Feiten en cijfers versterken je overtuigingskracht."},
    {"type": "invul", "vraag": "Complete the phrase: <i>The main reason ... we need urgent action is global warming.</i>", "antwoord": "why|that", "uitleg": "'The main reason why/that...' (de belangrijkste reden waarom)."},
    {"type": "mc", "vraag": "Which phrase is an effective call to action at the end of a green speech?", "opties": ["Together, we can make our school greener and cleaner! Let's act today!", "I am done talking so you can go home.", "Who cares about the environment anyway?", "Please give me five euros."], "antwoord": 0, "uitleg": "Een motiverende oproep tot actie."},
    {"type": "mc", "vraag": "What does <b>greenwashing</b> mean in environmental discussions?", "opties": ["Making misleading or false claims about the environmental benefits of a product or company", "Washing green clothes in cold water", "Painting dirty factory walls green", "Watering organic plants in a greenhouse"], "antwoord": 0, "uitleg": "Greenwashing is het ten onrechte groener voordoen van producten of bedrijven."},
    {"type": "waaronwaar", "vraag": "The phrase <i>'We could easily replace disposable cups with reusable mugs'</i> proposes a practical green solution.", "antwoord": True, "uitleg": "Waar. Dit is een concrete en haalbare suggestie."},
    {"type": "invul", "vraag": "Complete the proposal opening: <i>We ... that the school introduces meat-free Mondays.</i>", "antwoord": "propose|suggest|recommend", "uitleg": "We propose / suggest / recommend."},
    {"type": "mc", "vraag": "How do you emphasize a strong point during a presentation?", "opties": ["I would like to emphasize that every single action counts.", "Look at my shoes while I speak.", "This slide has no meaning.", "Forget everything I just said."], "antwoord": 0, "uitleg": "'I would like to emphasize that...' legt duidelijke nadruk."},
    {"type": "open", "vraag": "Write a short persuasive argument for banning single-use water containers in the cafeteria.", "sleutelwoorden": ["waste/plastic/pollution/ocean", "refillable/reusable/bottles/clean/environment"], "minTreffers": 1, "modelantwoord": "Banning single-use plastic bottles drastically reduces plastic waste, and students can easily refill reusable bottles at water stations.", "uitleg": "Een overtuigend argument benoemt de vermindering van afval en het herbruikbare alternatief."},
    {"type": "mc", "vraag": "Which phrase expresses partial agreement with a classmate?", "opties": ["I agree with you up to a point, but we must also consider the budget.", "You are 100% wrong about everything.", "I agree with everything unconditionally forever.", "I have no thoughts on this matter."], "antwoord": 0, "uitleg": "'I agree up to a point, but...' toont gedeeltelijke instemming."},
    {"type": "waaronwaar", "vraag": "In a formal debate, interrupting the other speaker with loud insults is considered good manners.", "antwoord": False, "uitleg": "Onwaar. In een formeel debat laat je elkaar uitspreken en blijf je beleefd."},
    {"type": "invul", "vraag": "Fill in the connector: <i>On the ... hand it costs money; on the other hand it saves nature.</i>", "antwoord": "one", "uitleg": "'On the one hand'."},
    {"type": "mc", "vraag": "What is the benefit of using <i>rhetorical questions</i> in an environmental speech?", "opties": ["They make the audience reflect deeply on the issue without expecting an immediate spoken answer", "They test the audience on difficult mathematical equations", "They give the speaker time to drink coffee", "They translate the speech into Dutch"], "antwoord": 0, "uitleg": "Retorische vragen zetten het publiek aan het denken."},
    {"type": "waaronwaar", "vraag": "The phrase <i>'Scientific consensus'</i> means that the overwhelming majority of scientists agree on a conclusion.", "antwoord": True, "uitleg": "Waar. Wetenschappelijke consensus betekent brede overeenstemming."},
    {"type": "invul", "vraag": "Complete the phrase: <i>There is clear scientific ... that global temperatures are rising.</i>", "antwoord": "evidence|proof|data", "uitleg": "Clear scientific evidence / proof."},
    {"type": "mc", "vraag": "Which phrase summarizes the key message of a proposal?", "opties": ["In conclusion, taking green action now will safeguard our future.", "Secondly, open the door.", "Why is the window open?", "The clock shows 3 PM."], "antwoord": 0, "uitleg": "Een krachtige samenvattende slotzin."}
  ]
}

# EXAMEN 24: H5 Reading & Climate Texts (20 questions)
ex24 = {
  "id": "ex-h3-eng-24",
  "hoofdstuk": 5,
  "hoofdstukTitel": "Hoofdstuk 5 — Going green",
  "titel": "Toets 4 — Reading Skills: Climate Articles, Facts vs. Opinions",
  "vak": "Engels · HAVO 3 (H5)",
  "icoon": "📰",
  "duurMin": 25,
  "vragen": [
    {"type": "mc", "vraag": "What is the crucial difference between a <b>fact</b> and an <b>opinion</b> in an environmental article?", "opties": ["A fact can be proven true with objective evidence, while an opinion expresses a personal belief or feeling", "A fact is always written in bold font, while opinions are underlined", "There is no difference in modern journalism", "Facts only relate to sports results"], "antwoord": 0, "uitleg": "Een feit is controleerbaar en bewezen; een mening is een persoonlijke opvatting."},
    {"type": "mc", "vraag": "Which of the following is an objective <b>fact</b>?", "opties": ["Carbon dioxide is a greenhouse gas that traps thermal radiation.", "Electric cars are the most beautiful vehicles ever built.", "Winter in the Netherlands is far too boring.", "Solar panels look ugly on old houses."], "antwoord": 0, "uitleg": "Dit is een wetenschappelijk bewezen natuurkundig feit."},
    {"type": "waaronwaar", "vraag": "The statement <i>'Cycling to school is much more enjoyable than taking the bus'</i> is an objective scientific fact.", "antwoord": False, "uitleg": "Onwaar. Dit is een persoonlijke mening (opinion)."},
    {"type": "invul", "vraag": "Fill in the reading term: <i>A statement that can be verified with empirical evidence is a ... .</i>", "antwoord": "fact", "uitleg": "A fact is een controleerbaar feit."},
    {"type": "mc", "vraag": "What is the author's primary <b>purpose</b> in a persuasive environmental opinion piece (op-ed)?", "opties": ["To convince readers to adopt sustainable habits and support green policies", "To sell secondhand diesel trucks", "To entertain toddlers with bedtime fairy tales", "To list the train departure times to Berlin"], "antwoord": 0, "uitleg": "De lezer overtuigen van duurzaam beleid en gedragsverandering."},
    {"type": "waaronwaar", "vraag": "Adjectives like <i>terrible, wonderful, ridiculous, essential</i> often signal that the author is expressing an opinion.", "antwoord": True, "uitleg": "Waar. Subjectieve bijvoeglijke naamwoorden wijzen op een mening."},
    {"type": "invul", "vraag": "Fill in the reading term: <i>A personal viewpoint that cannot be proven 100% true or false is an ... .</i>", "antwoord": "opinion", "uitleg": "An opinion is een mening."},
    {"type": "mc", "vraag": "What is the function of quotation marks (\" \") when quoting climate scientists in an article?", "opties": ["To indicate the exact spoken or written words of an expert source", "To show that the words are completely made up", "To hide the scientist's name from readers", "To indicate the words are in Latin"], "antwoord": 0, "uitleg": "Aanhalingstekens tonen een letterlijk citaat van een expert."},
    {"type": "mc", "vraag": "What does <b>bias</b> mean in news reporting?", "opties": ["An unfair preference for or prejudice against one particular perspective or party", "The ability to write very fast on a typewriter", "Printing photographs in black and white", "Using simple everyday vocabulary"], "antwoord": 0, "uitleg": "Bias is partijdigheid of bevooroordeeldheid."},
    {"type": "waaronwaar", "vraag": "Reliable climate reporting relies on peer-reviewed scientific studies published in recognized journals.", "antwoord": True, "uitleg": "Waar. Geverifieerde studies vormen de basis voor betrouwbare verslaggeving."},
    {"type": "invul", "vraag": "Fill in the noun (bron): <i>Always check if the information comes from a reputable and trustworthy ... .</i>", "antwoord": "source", "uitleg": "A reliable source is een betrouwbare bron."},
    {"type": "mc", "vraag": "Why do journalists include real-world case studies in articles about climate change?", "opties": ["To illustrate how abstract global statistics directly impact human lives and communities", "To fill blank space on the page", "To avoid conducting real interviews", "To translate numbers into words"], "antwoord": 0, "uitleg": "Praktijkvoorbeelden maken abstracte klimaatcijfers tastbaar en invoelbaar."},
    {"type": "open", "vraag": "Explain why identifying an author's bias is important when reading articles about energy subsidies.", "sleutelwoorden": ["financial/interests/sponsor/money", "critical/objective/perspective/fairness"], "minTreffers": 1, "modelantwoord": "Recognizing bias helps readers understand if the author has financial or political interests, allowing for a critical evaluation of the arguments.", "uitleg": "Het herkennen van partijdigheid helpt om argumenten kritisch te beoordelen op eventuele belangenverstrengeling."},
    {"type": "mc", "vraag": "Which phrase indicates that the author is drawing a final conclusion from the presented data?", "opties": ["In light of these findings, it is clear that emissions must be reduced immediately.", "Secondly, let us discuss football.", "The weather was cloudy yesterday.", "Nobody knows how to read graphs."], "antwoord": 0, "uitleg": "Concludeert helder op basis van de gepresenteerde onderzoeksresultaten."},
    {"type": "waaronwaar", "vraag": "A chart showing rising global temperatures over the past 150 years provides quantitative empirical evidence.", "antwoord": True, "uitleg": "Waar. Grafieken leveren meetbare kwantitatieve data."},
    {"type": "invul", "vraag": "Fill in the missing word: <i>The author presents strong arguments to ... her hypothesis.</i>", "antwoord": "support|prove|back", "uitleg": "Support / prove / back her hypothesis."},
    {"type": "mc", "vraag": "What is meant by a <b>call to action</b> at the end of an editorial?", "opties": ["An explicit appeal urging readers to take specific steps or change their behavior", "An emergency phone call to the local fire station", "A demand for readers to pay subscription fees", "A list of upcoming television programs"], "antwoord": 0, "uitleg": "Een oproep tot concrete actie aan de lezers."},
    {"type": "waaronwaar", "vraag": "Headlines in tabloid newspapers are always 100% neutral and never use sensational exaggeration.", "antwoord": False, "uitleg": "Onwaar. Sensatiekranten gebruiken vaak overdreven koppen om aandacht te trekken."},
    {"type": "invul", "vraag": "Complete the phrase: <i>The data ... (to show) a steady decline in Arctic sea ice.</i>", "antwoord": "shows|indicates|reveals", "uitleg": "The data shows / indicates."},
    {"type": "mc", "vraag": "What does a balanced journalistic article do?", "opties": ["Presents multiple perspectives and evidence fairly before drawing well-supported conclusions", "Attacks anyone who disagrees with angry language", "Copies social media posts without fact-checking", "Publishes only commercial advertisements"], "antwoord": 0, "uitleg": "Evenwichtige journalistiek belicht meerdere invalshoeken op basis van feiten."}
  ]
}

# EXAMEN 25: H5 Hoofdstuk Eindtoets (Mix & Sınav Simülasyonu) (20 questions)
ex25 = {
  "id": "ex-h3-eng-25",
  "hoofdstuk": 5,
  "hoofdstukTitel": "Hoofdstuk 5 — Going green",
  "titel": "Toets 5 — Hoofdstuk 5 Eindtoets (Mix & Examen)",
  "vak": "Engels · HAVO 3 (H5)",
  "icoon": "🏆",
  "duurMin": 30,
  "vragen": [
    {"type": "mc", "vraag": "What is the definition of <b>carbon footprint</b>?", "opties": ["The total greenhouse gas emissions caused directly and indirectly by an individual or organization", "The physical trace left by hiking shoes in wet soil", "A trademark logo for recycled footwear", "The soot produced by a domestic fireplace"], "antwoord": 0, "uitleg": "Carbon footprint is de totale uitstoot van broeikasgassen door iemands levensstijl."},
    {"type": "mc", "vraag": "Choose the correct First Conditional sentence:", "opties": ["If we recycle more paper, we will save precious forests.", "If we will recycle more paper, we save forests.", "If we recycle paper, we would saved forests.", "If we will recycle, we will save forests."], "antwoord": 0, "uitleg": "If + Present Simple (recycle), resultaat = will + hele werkwoord (will save)."},
    {"type": "waaronwaar", "vraag": "<b>Deforestation</b> means planting large numbers of native trees across barren hillsides.", "antwoord": False, "uitleg": "Onwaar. Deforestation is grootschalige ontbossing en houtkap."},
    {"type": "invul", "vraag": "Fill in the English adjective (duurzaam / hernieuwbaar): <i>Wind and solar power are forms of ... energy.</i>", "antwoord": "renewable|sustainable|green", "uitleg": "Renewable / sustainable energy."},
    {"type": "mc", "vraag": "Which phrase is the most natural way to suggest a green initiative?", "opties": ["Why don't we set up a student sustainability committee?", "Why don't we to set up a committee?", "How about to set up a committee?", "Let's to set up a committee."], "antwoord": 0, "uitleg": "'Why don't we + hele werkwoord' (set up)."},
    {"type": "waaronwaar", "vraag": "Products labeled <b>eco-friendly</b> are engineered to cause minimal harm to natural ecosystems.", "antwoord": True, "uitleg": "Waar. Eco-friendly betekent milieuvriendelijk."},
    {"type": "invul", "vraag": "Fill in the missing word: <i>Look at those dark clouds; it is ... to rain!</i>", "antwoord": "going", "uitleg": "'It is going to rain' bij direct zichtbaar bewijs."},
    {"type": "mc", "vraag": "What does <b>biodiversity</b> encompass?", "opties": ["The total variety of plant, animal, and microscopic life within an ecosystem", "The speed of ocean currents during winter storms", "The electrical voltage of solar batteries", "The weight of municipal waste trucks"], "antwoord": 0, "uitleg": "Biodiversiteit is de verscheidenheid aan levensvormen in een leefgebied."},
    {"type": "mc", "vraag": "Choose the correct future response for a spontaneous decision:", "opties": ["The room is cold; I'll close the window!", "The room is cold; I am closing the window yesterday.", "The room is cold; I close the window every decade.", "The room is cold; I have closed it since."], "antwoord": 0, "uitleg": "Spontaan besluit ter plekke -> 'will' / 'I'll'."},
    {"type": "waaronwaar", "vraag": "In First Conditional sentences, using <i>will</i> inside the <i>if-clause</i> is standard grammatical English.", "antwoord": False, "uitleg": "Onwaar. In het if-deel mag NOOIT will staan."},
    {"type": "invul", "vraag": "Fill in the noun (bedreigde soort): <i>The black rhino is a critically ... species.</i>", "antwoord": "endangered", "uitleg": "Endangered species betekent bedreigde diersoort."},
    {"type": "mc", "vraag": "What is the primary function of a <b>wind turbine</b>?", "opties": ["To generate clean renewable electricity from the kinetic power of the wind", "To blow hot air over coastal beaches", "To measure the speed of passing aircraft", "To pump groundwater into swimming pools"], "antwoord": 0, "uitleg": "Windturbines zetten windenergie om in schone elektriciteit."},
    {"type": "open", "vraag": "Why is international cooperation crucial to tackling climate challenges?", "sleutelwoorden": ["worldwide/borders/share/atmosphere/pollution", "cooperate/together/treaty/collective/planet"], "minTreffers": 1, "modelantwoord": "Greenhouse gases and pollution affect the entire planet across national borders, so all countries must cooperate to cut global emissions.", "uitleg": "Klimaatverandering treft de hele aarde grensoverschrijdend; gezamenlijke actie is noodzakelijk."},
    {"type": "mc", "vraag": "How do you present contrasting arguments fairly in an environmental debate?", "opties": ["On the one hand..., but on the other hand...", "First of all..., and finally...", "Because of..., despite of...", "Since Monday..., until Friday..."], "antwoord": 0, "uitleg": "'On the one hand..., on the other hand...' weegt voor- en nadelen af."},
    {"type": "waaronwaar", "vraag": "<b>Organic farming</b> relies heavily on synthetic chemical pesticides to maximize harvest speed.", "antwoord": False, "uitleg": "Onwaar. Biologische landbouw vermijdt chemische bestrijdingsmiddelen."},
    {"type": "invul", "vraag": "Complete the First Conditional: <i>If sea levels rise, low-lying coastal areas ... flood.</i>", "antwoord": "will", "uitleg": "Resultaat = will flood."},
    {"type": "mc", "vraag": "What does <b>greenwashing</b> mean?", "opties": ["Deceptively advertising a product as environmentally friendly when it is not", "Cleaning industrial machinery with organic soap", "Painting public park benches in green paint", "Growing tomatoes in glass greenhouses"], "antwoord": 0, "uitleg": "Greenwashing is het misleidend 'groen' presenteren van vervuilende producten."},
    {"type": "waaronwaar", "vraag": "The negative contracted form of <i>will not</i> is <i>won't</i>.", "antwoord": True, "uitleg": "Waar. Won't = will not."},
    {"type": "invul", "vraag": "Complete the suggestion: <i>How about ... (to organise) a beach clean-up event this weekend?</i>", "antwoord": "organising|organizing", "uitleg": "'How about' + -ing (organising / organizing)."},
    {"type": "mc", "vraag": "What is the difference between a fact and an opinion?", "opties": ["A fact can be proven true with evidence; an opinion reflects personal feelings or beliefs", "A fact is only spoken; an opinion is always written", "A fact has ten words; an opinion has five", "There is no difference in modern English"], "antwoord": 0, "uitleg": "Feiten zijn bewezen en controleerbaar; meningen zijn persoonlijke opvattingen."}
  ]
}

write_examen("examen_21.js", ex21)
write_examen("examen_22.js", ex22)
write_examen("examen_23.js", ex23)
write_examen("examen_24.js", ex24)
write_examen("examen_25.js", ex25)
print("Hoofdstuk 5 exams (21 to 25) generated successfully!")
